--
-- PostgreSQL database dump
--

\restrict 2dcxTCzIZ84c8OLcYgx6fcUceSakbLrcicgwFHViQ8hY9ThTlh0ZkWvW941uMla

-- Dumped from database version 18.1 (Debian 18.1-2)
-- Dumped by pg_dump version 18.1 (Debian 18.1-2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: reservations; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.reservations (
    id bigint NOT NULL,
    date_reservation date,
    montant_total double precision NOT NULL,
    statut_paiement character varying(255),
    utilisateur_id bigint,
    salle_id bigint
);


ALTER TABLE public.reservations OWNER TO my_user;

--
-- Name: reservations_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.reservations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: salles; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.salles (
    id bigint NOT NULL,
    capacite integer NOT NULL,
    image_url character varying(255),
    localisation character varying(255),
    nom character varying(255),
    prix_journalier double precision NOT NULL
);


ALTER TABLE public.salles OWNER TO my_user;

--
-- Name: salles_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.salles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.salles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: utilisateurs; Type: TABLE; Schema: public; Owner: my_user
--

CREATE TABLE public.utilisateurs (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    mot_de_passe character varying(255),
    nom character varying(255),
    role character varying(255),
    telephone character varying(255)
);


ALTER TABLE public.utilisateurs OWNER TO my_user;

--
-- Name: utilisateurs_id_seq; Type: SEQUENCE; Schema: public; Owner: my_user
--

ALTER TABLE public.utilisateurs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.utilisateurs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: reservations; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.reservations (id, date_reservation, montant_total, statut_paiement, utilisateur_id, salle_id) FROM stdin;
1	2026-02-15	200000	PAYE	4	3
\.


--
-- Data for Name: salles; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.salles (id, capacite, image_url, localisation, nom, prix_journalier) FROM stdin;
1	500	https://images.pexels.com/photos/14636315/pexels-photo-14636315.jpeg	Cotonou, Fidjrossè	Palais de Cristal	250000
2	300	https://images.pexels.com/photos/5812870/pexels-photo-5812870.jpeg	Cadjehoun	Salle La Marquise	200000
3	150	https://images.pexels.com/photos/30311728/pexels-photo-30311728.jpeg	Cotonou Haie vive	Salle Les Saints de Germain	200000
4	300	https://images.pexels.com/photos/9080091/pexels-photo-9080091.jpeg	Fidjrossè	Majestic	350000
5	300	https://images.pexels.com/photos/33852660/pexels-photo-33852660.jpeg	Calavi IITA	Padre Pio	100000
6	200	https://images.pexels.com/photos/34672233/pexels-photo-34672233.jpeg	St Michel	Sainte Cécile	150000
\.


--
-- Data for Name: utilisateurs; Type: TABLE DATA; Schema: public; Owner: my_user
--

COPY public.utilisateurs (id, email, mot_de_passe, nom, role, telephone) FROM stdin;
1	admin@atlas.com	admin123	Emmanuel Admin	ADMIN	01020304
2	client@atlas.com	1234	Jean Client	CLIENT	05060708
3	dociviw764@gmail.com	\N	Houriath VO	CLIENT	0198765432
4	jeandalle@gmail.com	1234	Jean Dalle	CLIENT	+2290134567890
\.


--
-- Name: reservations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.reservations_id_seq', 1, true);


--
-- Name: salles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.salles_id_seq', 6, true);


--
-- Name: utilisateurs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: my_user
--

SELECT pg_catalog.setval('public.utilisateurs_id_seq', 4, true);


--
-- Name: reservations reservations_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT reservations_pkey PRIMARY KEY (id);


--
-- Name: salles salles_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.salles
    ADD CONSTRAINT salles_pkey PRIMARY KEY (id);


--
-- Name: utilisateurs uk6ldvumu3hqvnmmxy1b6lsxwqy; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.utilisateurs
    ADD CONSTRAINT uk6ldvumu3hqvnmmxy1b6lsxwqy UNIQUE (email);


--
-- Name: utilisateurs utilisateurs_pkey; Type: CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.utilisateurs
    ADD CONSTRAINT utilisateurs_pkey PRIMARY KEY (id);


--
-- Name: reservations fk11c2598mdsm9g395pl5ubdvi3; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fk11c2598mdsm9g395pl5ubdvi3 FOREIGN KEY (salle_id) REFERENCES public.salles(id);


--
-- Name: reservations fk5jh2b3gs43v5mdq0ocumvv34p; Type: FK CONSTRAINT; Schema: public; Owner: my_user
--

ALTER TABLE ONLY public.reservations
    ADD CONSTRAINT fk5jh2b3gs43v5mdq0ocumvv34p FOREIGN KEY (utilisateur_id) REFERENCES public.utilisateurs(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO my_user;


--
-- PostgreSQL database dump complete
--

\unrestrict 2dcxTCzIZ84c8OLcYgx6fcUceSakbLrcicgwFHViQ8hY9ThTlh0ZkWvW941uMla

